[project]
name = "TaskMaster"
version = "0.0.1"
description = """Web-based Task Management application that makes use heavily of django full stack
ability"""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
	"django[argon2]>=5.2.1",
	"django-allauth[socialaccount]>=65.9.0",
	"django-colorfield>=0.14.0",
	"django-cors-headers>=4.7.0",
	"django-environ>=0.12.0",
	"django-htmx>=1.23.0",
	"djangorestframework>=3.16.0",
	"gunicorn>=26.0.0",
	"whitenoise>=6.12.0",
	"celery[redis]>=5.6.3",
	"psycopg[binary]>=3.3.4",
]
authors = [{ name = "Andrew Anter", email = "andrew.anter@gmail.com" }]

[tool.basedpyright]
include = ["."]
exclude = ["**/node_modules", "**/__pycache__", ".venv", "**/migrations/*.py", "src"]
typeCheckingMode = "standard"
stubPath = "./typings/"


[dependency-groups]
dev = [
	"bandit>=1.8.0",
	"basedpyright>=1.30.0",
	"django-stubs>=5.2.0",
	"django-stubs-ext>=5.2.0",
	"django-types>=0.21.0",
	"playwright>=1.62.0",
	"pyopenssl>=25.1.0",
	"pytest>=8.4.1",
	"pytest-django>=4.11.1",
	"werkzeug>=3.1.3",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["test_*.py", "*_test.py", "*/tests/*.py", "*/tests.py"]

[tool.bandit]
exclude_dirs = [".venv", ".git", "staticfiles", "typings", "src", "node_modules"]
skips = ["B101"]
