# Generated by Django 5.2.1 on 2025-05-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['status', 'priority', 'due_date'], 'verbose_name': 'To-Do Item', 'verbose_name_plural': 'To-Do Items'},
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High'), (0, 'None')], default=2),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
