# Generated by Django 5.2.1 on 2025-05-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_options_remove_todoitem_completed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem',
            new_name='Task',
        ),
    ]
