# Generated by Django 5.2.1 on 2025-06-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_rename_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due date & time'),
        ),
    ]
