# Generated by Django 5.2.1 on 2026-06-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0002_remove_label_tasks_label_owner"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="labels.label"
            ),
        ),
    ]
