# Generated by Django 5.2.1 on 2026-06-06 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0002_remove_label_tasks_label_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
