# Generated by Django 5.2.1 on 2026-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_dedupe_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
