# Generated by Django 5.2.1 on 2026-08-15 17:59

from django.conf import settings
from django.db import migrations, models


def backfill_read_at(apps, schema_editor):
    """Preserve read state for rows created before ``read_at`` existed: use
    ``created_at`` as the read timestamp for previously-read notifications."""
    Notification = apps.get_model("notifications", "Notification")
    Notification.objects.filter(is_read=True, read_at__isnull=True).update(
        read_at=models.F("created_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0004_notification_read_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_read_at, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_recipie_4e3567_idx",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read_at"], name="notificatio_recipie_564b1f_idx"
            ),
        ),
    ]
